### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by uxo2** [uxo2/xyz-t#19]
## TodoList

- 缩放时标尺
- 预览模式，单页面预览和整体项目预览
- 右键新建项目和页面
- 样式IDE配置
- js脚本配置
- 资源管理器动态显示隐藏
- 登录退出
- 引导页面
- 全局loading状态
- 本地缓存数据
- http 请求和mock拦截数据
- 组件树动态响应选中组件
- 组件树右键绑定复制、乡下复制、删除、剪切、插入
- 新增容器排版
- 新增虚拟弹框
- 虚拟页面与主页面canvas连线配置
- 富文本功能联通样式配置。参考excel配置样式
- progress动态响应请求loading 尽量减少弹框出现频率
- 静态资源上传，搭建静态服务器。
- 自动保存关闭和开启
- 撤销回滚机制npm配置
- 辅助边框线配置，屏幕配置全局样式，背景样式、长度、宽度等。

高级功能：

多人协同操作。
部署、构建环境
源码导出、组件导出
模板市场
高级业务组件封装

多三方UI渲染库。
element2x 3x  
Antd-Design
material
vant
NutUI
bootstrap4
Mint UI

UI库、解析库、模板库合并到一个NPM包。
再加一个第三方自定义UI库、解析库、模板库。

-----

- 只有解锁后的项目才可以编辑。
- 锁定后只能预览，不可编辑、部署等其他操作。
- 删除需要有一个回滚记录
- 撤销回滚保存属性配置值
- demo不可删除

### 影响因素

- [ ] 高亮边框引发的`outline:2px`。
- [ ] 边框画板区域和预览区域存在的默认border问题（辅助边框线问题）。

细节配置

- [ ] 所有lable、文本等文字显示均可自动编辑状态
- [ ] 图标点击可编辑弹框切换图标
-  [ ] 快捷键add： 全选操作， shift + ctrl + A + Z + C
- [ ] 输入框长度增加配置，长度自定义或者全宽。
- [ ] 浮动移除，宽度配置百分比。组件配置display: inline-block or inline-flex.
- [ ] 所有控件之间默认间距3px： 1px 存放border配置。  1px存放高亮选中，1px防止选中的z-index层级过低
- [ ] 画板区域输入框增加v-model。可输入、可编辑，用于正则、实时显示及其错误信息展示。oc: 减少preview次数。
- [ ] 基础容器默认为flex布局， 设计： 若无children => 默认padding: 10px， 填充内容用于拖动内部
- [ ] 鼠标draggable设置拖动图片在画板内部的组件相互拖动。
- [ ] 工作台需求列表
- [ ] 增加显示/隐藏边框的功能
- [ ] 增加快速配置样式上下左右居中的按钮
- [ ] 增加虚拟悬浮层位置
- [ ] 增加粘附功能：组件、辅助定位线
- [ ] 移除sortablejs排序npm包，采用自定义托拉拽功能
- [ ] 增加一键部署主题功能
- [ ] 拆分element基础控件，自定义基础控件，一步步移除element pkg
- [ ] 针对不同公司内部项目推动theme配置方案，与自定义组件耦合
- [ ] 针对样式布局采用vscode、华为魔方设计
- [ ] 基础设计都是以现实为主，满足二次开发需求
- [ ] 预留一套代码多端支持的未来设计功能
- [ ] 针对多人协作构建中型项目的设计蓝图，资源的分配、锁定和其他配套功能
- [ ] 预览地址即线上部署效果，采用url地址跳转方式。
- [ ] 所有基础控件hover显示基础信息：宽高、字体、背景
- [ ] 预留form组件渲染，整体页面div局部form包裹
- [ ] form组件内包裹form-item表单组件，未包裹则为基础组件
- [ ] 全局流式布局，局部细节相对外部，绝对内部布局
- [ ] 预览模式多屏展示
- [ ] 撤销重构针对细致化到属性
- [ ] 显示每个基础控件的代码，用户可以自定义编辑
- [ ] 基础控件关联多个theme相同控件。（基础控件按钮有十几个theme和已经绑定的事件组合的模板列表）
- [ ] 新建项目时默认自带多个静态资源。图标、字体、图片、npm包
- [ ] 增加容器嵌套行规则，箭头指向(举例： 页面>表单>容器>输入框)。
- [ ] iframe配置body背景样式
- [ ] 防连点，保存、请求、筛选等接口或者高频率高功耗API

**Comment by uxo2** [comment]
## 所见即所(WYSIWYG)细节点配置

画板区域很难保证所见即所得的视觉效果，因此退后一步，采用逐步向上兼容方式尽可能满足其视觉效果。
并且为了控制错误在可控范围，因此需要针对其他特殊的属性配置、css样式、html标签尽可能的统一化和标准化。

- [ ] 高亮边框引发的`outline:2px`
- [ ] 边框画板区域和预览区域存在的默认border问题（辅助边框线问题）
- [x] 已打开文件列表新增右键：关闭右侧、关闭左侧 #18 
- [x] 未打开文件时的空白页面ui   #21 
- [ ]引导功能
- [ ] mock数据及其顶部进度条
- [ ] 预览页面ui
- [ ] 反馈页面
- [ ] 用户账号页面
- [ ] 全局setting.json文件配置
- [ ] 样式IDE配置
- [ ] 组件树右键：复制、向下复制、删除、剪切、插入
- [ ] 自动保存功能及其配置开启和关闭
- [ ] 本地缓存localforage
- [ ] 项目功能更新日志存储在版本页中
- [ ] 增加CI/CD
- [ ] 所有lable、文本等文字显示均可自动编辑状态
- [ ] 图标点击可编辑弹框切换图标
-  [ ] 快捷键add： 全选操作， shift + ctrl + A + Z + C
- [ ] 输入框长度增加配置，长度自定义或者全宽。
- [ ] 浮动移除，宽度配置百分比。组件配置display: inline-block or inline-flex.
- [ ] 所有控件之间默认间距3px： 1px 存放border配置。  1px存放高亮选中，1px防止选中的z-index层级过低
- [ ] 画板区域输入框增加v-model。可输入、可编辑，用于正则、实时显示及其错误信息展示。oc: 减少preview次数。
- [ ] 基础容器默认为flex布局， 设计： 若无children => 默认padding: 10px， 填充内容用于拖动内部
- [ ] 鼠标draggable设置拖动图片在画板内部的组件相互拖动。
- [ ] 工作台需求列表
- [ ] 增加显示/隐藏边框的功能
- [ ] 增加快速配置样式上下左右居中的按钮
- [ ] 增加虚拟悬浮层位置
- [ ] 增加粘附功能：组件、辅助定位线
- [ ] 移除sortablejs排序npm包，采用自定义托拉拽功能
- [ ] 增加一键部署主题功能
- [ ] 拆分element基础控件，自定义基础控件，一步步移除element pkg
- [ ] 针对不同公司内部项目推动theme配置方案，与自定义组件耦合
- [ ] 针对样式布局采用vscode、华为魔方设计
- [ ] 基础设计都是以现实为主，满足二次开发需求
- [ ] 预留一套代码多端支持的未来设计功能
- [ ] 针对多人协作构建中型项目的设计蓝图，资源的分配、锁定和其他配套功能
- [ ] 预览地址即线上部署效果，采用url地址跳转方式。
- [ ] 所有基础控件hover显示基础信息：宽高、字体、背景
- [ ] 预留form组件渲染，整体页面div局部form包裹
- [ ] form组件内包裹form-item表单组件，未包裹则为基础组件
- [ ] 全局流式布局，局部细节相对外部，绝对内部布局
- [ ] 预览模式多屏展示
- [ ] 撤销重构针对细致化到属性
- [ ] 显示每个基础控件的代码，用户可以自定义编辑
- [ ] 基础控件关联多个theme相同控件。（基础控件按钮有十几个theme和已经绑定的事件组合的模板列表）
- [ ] 新建项目时默认自带多个静态资源。图标、字体、图片、npm包
- [ ] 增加容器嵌套行规则，箭头指向(举例： 页面>表单>容器>输入框)。
- [ ] iframe配置body背景样式
- [ ] 防连点，保存、请求、筛选等接口或者高频率高功耗API

**Comment by uxo2** [comment]
## 解锁、锁定机制 #16 

多人协同操作问题的解决方案是增加一个解锁和锁定的机制。

只有解锁后的项目，才能进行增删改查等操作。未解锁的项目或者页面只提供预览功能。

同一时刻仅有一个账号能对一个项目进行解锁，如需要对其他项目进行解锁，则必须释放锁资源。

**Comment by uxo2** [comment]
# 谈谈coding业务的问题


这个项目究竟要不要过多的涉及到私有公司内部的业务属性上， 还是坚持传统的满足大部分公共组件上去，这是一个很难抉择的问题， 前者容易坠入到无尽的业务coding上，后者容易脱离真实需求环境，仅仅作为一个自我陶醉的开源项目中。 

我考虑了很久，决定这部分还是由公司内部自研封装，我只负责全局框架的事情。尽可能的搭建起一套适用于大部分业务场景的框架， 不接业务环节。 

在可预期的未来，xyz-t项目还能够保持更新一年内。若一年后效果良好则考虑转企业级服务产品。若不好，似乎我的目的也达到了，还就彻底抛弃此项目。

**Comment by uxo2** [comment]
## 大屏统计

实时更新显示用户操作日志，包括不限于：

- 项目路径图线形图
- 页面更新热力图类 `Github commit`图
- 历史版本日志图
- 发布版本

**Comment by uxo2** [comment]
## 属性太多繁杂乱问题

- [ ] 增加智能search提示信息，定向制定属性配置项。 举例： 全屏 居中 固定 fixed  布局等直接配置，输入直接配置。无需查找。
- [ ] 增加可视化排版配置、react-grid-layout 等全屏配置。

**Comment by uxo2** [comment]
## 可视化动画效果

需求： 需要增加一个全方位的可视化项目页面之间关系的视觉效果。

功能点： 
- [ ] canvas动画演示，渲染每个基础页面并采用工作流的形式进行关联页面，其中可以增加部分功能配置，举例：连线更改（变量更新， 反之依然）
- [ ] 数据流图， 每个基础的变量都是一个全局的数据field，并进行相关的分离，数据字段、弹框visible类型，跳转类型等等。
- [ ] 由于数据都是全局变量， 因此只能使用中小型项目（移动端一半不超过20个页面，PC端10个页面），一旦过大、全局数据量大无法分离，代码逻辑混乱、数据分离困难，最终导致二次研发难度增加。

**Comment by uxo2** [comment]
## 关于第三方UI库扩展问题探讨方案

目前该项目以rc-ts为基础，所以UI方面偏向rc， 然而市场上存在大量的ui库，这些ui库不可能全部独立完成， 工作量太大， 因此，需要有一个插件机制，由外部团队自行封装一套适配自己公司业务场景的UI库后再install到该项目中。


设计思路：

- 1、外部库统一封装为npm包格式（或者导入其他路径方式），统一在`xyz.install([...plugins])` 调用。
- 2、xyz.install 内部借鉴vue.install 模式，默认支持antdDeign、等其他库。

**Comment by uxo2** [comment]
## `domJson` 设计

常见的模式是使用tree格式进行嵌套形成dom， 在拖拉拽后的数据格式可直接渲染，但是在dom属性数据更新、查询、筛选中会出现大量的递归操作，而且页面越是复杂，dom嵌套层数越高，绘制页面时渲染时间越长，用户体验越差，这个是不可避免的大问题。

解决方向就是减少递归次数，尤其是在配置组件属性时的递归，这一点时需要考虑进去的。
1、解决方案1： dom扁平化。 由原先的tree结构打平为一维数组，存储和请求初始化较为直观。 然后，在初始渲染时再进行递归成一个dom-tree，优点：查询、删除、拖动、复制组件时效率较快，缺点：初始化时、数据传递iframe时需要增加一步递归操作。

**Comment by uxo2** [comment]
## 模板的重要性

推广项目最重要的不是基础组件，而是模板。

没有人愿意从零开始进行托拉拽绘制页面，只有从模板挑选进行初始绘制页面，才能保证快速的产出，二次研发也是基于模板进行二次研发， 而模板的数量取决于基础组件的数量质量。所以，我们的目标不是为了模板的基础点出发，也不是从组建的基础点出发，而是从业务的基础点出发。

第一步，搜索市场上绝大部分场景的功能，进行分分类。每一个类别代表着一个模板盒子， 这个盒子存放着大量的类似功能的模板，用户可以根据这个类别查找他需要的模板， 通常情况下可以满足大部分业务需求，极少数情况下需要针对选中的模板进行二次托拉拽配置，调用组件进行二次研发。这个才是正确的打开页面的方式。

第二步，大量结果表明， 一个成熟的互联网公司内部，对于前端业务都具有很大的相似性，而这项相似点很难被众多项目组统一使用，这样就导致浪费了大量的人力物力进行研发类似甚至相同的组件，于是为了解决这个问题，很多公司内部都有一套自研的UI库，来适应公司内部的业务， 但是这个UI库，在绝大部分场景下都是简单的UI主题的更改，针对业务的特殊性质确无法真正的统一，依然存在的大量的重复工作量。因此，为了解决这个问题，或者说为了降本增效，公司前端的业务、UI、基础逻辑、应该趋近于一个平衡线上，而这个平衡线就是前端的最高效点。这也是这个项目的目标。

第三步，不同的公司内部UI库的不同，很多中小型公司缺少自研的UI框架和业务沉淀库，因此这个点可以有xyz-t进行自我控制，通常选用市面上常用的组件库进行二次封装，element-ui  ant-design vant等，这是基础功能， 而针对拥有自研ui库、又有较强的安全意识的公司，那么在xyz中则需要提供一个可便于第三方库接入的功能，这一部分就由公司内部团队进行研发，当然为了减少他们团队的工作量， xyz需要提供一套常用的API接入这些UI库，提高xyz的二次研发能力，比如：

- 常规的模板接口
- 基础提供的UI库二次封装能力
- 整体页面的可视化点阵
- 数据可视化和足够的能力同步文档

**Comment by uxo2** [comment]
运维、产品、测试等非开发人员适用于模板简单的托拉拽配置简单页面。 这部分的开发任务侧重点在托拉拽绘制，（模板的生成更多的来自于开发人员）。

针对开发人员，不仅仅局限于简单的选择、托拉拽等选择性控制，更多的是输入型配置。输入型控制则更加的灵活和方便， 这也贴近开发人员的日常coding习惯。

那么贴近开发，尤其是前端开发的办公习惯。个人认为需要一个更高的门槛。


---

整个项目就变成：
- 外行配置简单页面，快捷方便，配置复杂页面不行
- 内行配置简答复杂（相对）页面， 快捷方便。

这个在大多数软件都是通用的逻辑。 excel office ps cad 等同理。

-----

这俩个方向大体是正确且可行性的。那么就侧重这俩方向进行构建设计文档、技术文档、操作指南等。
市场上大多数开源要么侧重其中一点，俩点同时兼备且分离明确的几乎没有。 这个需要有一个长时间的测试和验证才能行之有效。 微软的outsystem门槛极高，是专门针对开发人员的一套完整的低代码大型项目，且前后端都支持， 这个项目目前不考虑后端，仅仅考虑前端这一点。



---

2、为了未来的前后端联调的便捷性以及推广后的标准化，需要制定一个针对请求、异常、服务等众多方向的标准化sdk。
就请求而言， 百度的amis的请求设计给予了我灵感和启发。一个稳定的系统必定需要一个强有力的稳定且标准化的文档支撑着项目运转。 程序的灵活性和开发人员的灵活性太高， 这不利于项目的标准化和稳定。 所以需要有一个强有力、可被大众所接受的标准，而这套标准又是需要经历磨练不停的折中考虑后才比较合理。

因此，这个方向很难一个人完成，我所希望的是搭建一个当前开发人员普遍接受的基架，后期的二次开发就由其他项目组内自行配置（当然内部也嵌套了一个简单的模板参考，可满足大部分应用场景）。
