### ISSUE TITLE
todo-list 6/28~7/4

### ISSUE THREAD

**Issue by uxo2** [uxo2/xyz-t#4]
- [ ] file resources model combine opened list.
- [ ]  framework insert workbench container.
- [ ] add component `a-button` demo.
